# NumPy Basics

Find the numpy tutorial [here](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html).

NumPy’s main object is the homogeneous multidimensional array. In NumPy dimensions are called axes. The number of axes is rank.

A numpy array has different attributes defining its shape, number of dimensions, and the types of elements it contains.

In [15]:
import numpy as np
a = np.arange(15).reshape(3,5)
a
print(a.shape, a.ndim, a.dtype, a.itemsize)
type(a)

(3, 5) 2 int32 4


numpy.ndarray

## Creation of NumPy arrays 

In [41]:
a = [1,2,3]
arr = np.array(a)
print(type(a), type(arr))
np.array([(2,3,4), (5,6,7)])
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x

<class 'list'> <class 'numpy.ndarray'>


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

## Slicing

Find the basics of numpy slicing [here](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#indexing-slicing-and-iterating).

There is an important point to note when slicing a numpy array. Consider the array `x` defined above. Let's say we want to select the first element in the first axis (or dimension) of `x`. If we used a list to slice the first element as below, we get back an array with the same number of axes as before.

In [44]:
x[0:1,::]

array([[[1],
        [2],
        [3]]])

However, if we used a single number instead of a list, as shown below, then we reduce the number of dimension by 1. This reduction happens because we loose the first axiz since we picked out a single element from that axis instead of a list of numbers. Therefore, python doesn't need to store all the axes. 

In [43]:
x[0,::]

array([[[1],
        [2],
        [3]]])

More examples follow to make this point clear.

In [46]:
print(x[::,0])

[[1]
 [4]]


In [47]:
print(x[::,0:1])

[[[1]]

 [[4]]]


In [48]:
print(x[0,0,0])

1


In [49]:
print(x[0:1,0:1,0:1])

[[[1]]]


### Newaxis
Creates a new dimension in the array.

In [55]:
x[:,:,:]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [67]:
x[np.newaxis,:,:,:]

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]])